using System.Collections.Generic;
using System.Linq;

namespace HashcatGUI.Models;

public class HashMode
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;
    public string Example { get; set; } = string.Empty;
    public bool IsSlowHash { get; set; }

    public string DisplayName => $"{Id} - {Name}";

    public override string ToString() => DisplayName;

    public static List<HashMode> GetAllModes() => new()
    {
        // Raw Hash
        new() { Id = 0, Name = "MD5", Category = "Raw Hash", Example = "8743b52063cd84097a65d1633f5c74f5" },
        new() { Id = 10, Name = "md5($pass.$salt)", Category = "Raw Hash, Salted" },
        new() { Id = 20, Name = "md5($salt.$pass)", Category = "Raw Hash, Salted" },
        new() { Id = 30, Name = "md5(utf16le($pass).$salt)", Category = "Raw Hash, Salted" },
        new() { Id = 40, Name = "md5($salt.utf16le($pass))", Category = "Raw Hash, Salted" },
        new() { Id = 50, Name = "HMAC-MD5 (key = $pass)", Category = "Raw Hash, Authenticated" },
        new() { Id = 60, Name = "HMAC-MD5 (key = $salt)", Category = "Raw Hash, Authenticated" },
        new() { Id = 100, Name = "SHA1", Category = "Raw Hash", Example = "b89eaac7e61417341b710b727768294d0e6a277b" },
        new() { Id = 110, Name = "sha1($pass.$salt)", Category = "Raw Hash, Salted" },
        new() { Id = 120, Name = "sha1($salt.$pass)", Category = "Raw Hash, Salted" },
        new() { Id = 130, Name = "sha1(utf16le($pass).$salt)", Category = "Raw Hash, Salted" },
        new() { Id = 140, Name = "sha1($salt.utf16le($pass))", Category = "Raw Hash, Salted" },
        new() { Id = 150, Name = "HMAC-SHA1 (key = $pass)", Category = "Raw Hash, Authenticated" },
        new() { Id = 160, Name = "HMAC-SHA1 (key = $salt)", Category = "Raw Hash, Authenticated" },
        new() { Id = 200, Name = "MySQL323", Category = "Database Server" },
        new() { Id = 300, Name = "MySQL4.1/MySQL5", Category = "Database Server" },
        new() { Id = 400, Name = "phpass", Category = "Forums, CMS, E-Commerce" },
        new() { Id = 500, Name = "md5crypt, MD5 (Unix)", Category = "Operating System" },
        new() { Id = 501, Name = "Juniper IVE", Category = "Operating System" },
        new() { Id = 600, Name = "BLAKE2b-512", Category = "Raw Hash" },
        new() { Id = 900, Name = "MD4", Category = "Raw Hash" },
        new() { Id = 1000, Name = "NTLM", Category = "Operating System", Example = "b4b9b02e6f09a9bd760f388b67351e2b" },
        new() { Id = 1100, Name = "Domain Cached Credentials (DCC), MS Cache", Category = "Operating System" },
        new() { Id = 1300, Name = "SHA2-224", Category = "Raw Hash" },
        new() { Id = 1400, Name = "SHA2-256", Category = "Raw Hash", Example = "127e6fbfe24a750e72930c220a8e138275656b8e5d8f48a98c3c92df2caba935" },
        new() { Id = 1410, Name = "sha256($pass.$salt)", Category = "Raw Hash, Salted" },
        new() { Id = 1420, Name = "sha256($salt.$pass)", Category = "Raw Hash, Salted" },
        new() { Id = 1430, Name = "sha256(utf16le($pass).$salt)", Category = "Raw Hash, Salted" },
        new() { Id = 1440, Name = "sha256($salt.utf16le($pass))", Category = "Raw Hash, Salted" },
        new() { Id = 1450, Name = "HMAC-SHA256 (key = $pass)", Category = "Raw Hash, Authenticated" },
        new() { Id = 1460, Name = "HMAC-SHA256 (key = $salt)", Category = "Raw Hash, Authenticated" },
        new() { Id = 1500, Name = "descrypt, DES (Unix)", Category = "Operating System" },
        new() { Id = 1600, Name = "Apache $apr1$ MD5", Category = "FTP, HTTP, SMTP, LDAP Server" },
        new() { Id = 1700, Name = "SHA2-512", Category = "Raw Hash" },
        new() { Id = 1710, Name = "sha512($pass.$salt)", Category = "Raw Hash, Salted" },
        new() { Id = 1720, Name = "sha512($salt.$pass)", Category = "Raw Hash, Salted" },
        new() { Id = 1730, Name = "sha512(utf16le($pass).$salt)", Category = "Raw Hash, Salted" },
        new() { Id = 1740, Name = "sha512($salt.utf16le($pass))", Category = "Raw Hash, Salted" },
        new() { Id = 1750, Name = "HMAC-SHA512 (key = $pass)", Category = "Raw Hash, Authenticated" },
        new() { Id = 1760, Name = "HMAC-SHA512 (key = $salt)", Category = "Raw Hash, Authenticated" },
        new() { Id = 1800, Name = "sha512crypt $6$, SHA512 (Unix)", Category = "Operating System", IsSlowHash = true },
        new() { Id = 2100, Name = "Domain Cached Credentials 2 (DCC2), MS Cache 2", Category = "Operating System", IsSlowHash = true },
        new() { Id = 2400, Name = "Cisco-PIX MD5", Category = "Operating System" },
        new() { Id = 2410, Name = "Cisco-ASA MD5", Category = "Operating System" },
        new() { Id = 2500, Name = "WPA-EAPOL-PBKDF2", Category = "Network Protocol", IsSlowHash = true },
        new() { Id = 2501, Name = "WPA-EAPOL-PMK", Category = "Network Protocol" },
        new() { Id = 2600, Name = "md5(md5($pass))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 2611, Name = "vBulletin < v3.8.5", Category = "Forums, CMS, E-Commerce" },
        new() { Id = 2612, Name = "PHPS", Category = "Forums, CMS, E-Commerce" },
        new() { Id = 2711, Name = "vBulletin >= v3.8.5", Category = "Forums, CMS, E-Commerce" },
        new() { Id = 2811, Name = "MyBB 1.2+, IPB2+ (Invision Power Board)", Category = "Forums, CMS, E-Commerce" },
        new() { Id = 3000, Name = "LM", Category = "Operating System" },
        new() { Id = 3100, Name = "Oracle H: Type (Oracle 7+)", Category = "Database Server" },
        new() { Id = 3200, Name = "bcrypt $2*$, Blowfish (Unix)", Category = "Operating System", IsSlowHash = true },
        new() { Id = 3500, Name = "md5(md5(md5($pass)))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 3710, Name = "md5($salt.md5($pass))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 3800, Name = "md5($salt.$pass.$salt)", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 3910, Name = "md5(md5($pass).md5($salt))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 4010, Name = "md5($salt.md5($salt.$pass))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 4110, Name = "md5($salt.md5($pass.$salt))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 4300, Name = "md5(strtoupper(md5($pass)))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 4400, Name = "md5(sha1($pass))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 4500, Name = "sha1(sha1($pass))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 4520, Name = "sha1($salt.sha1($pass))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 4700, Name = "sha1(md5($pass))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 4710, Name = "sha1(md5($pass).$salt)", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 4800, Name = "iSCSI CHAP authentication", Category = "Network Protocol" },
        new() { Id = 4900, Name = "sha1($salt.$pass.$salt)", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 5100, Name = "Half MD5", Category = "Raw Hash" },
        new() { Id = 5200, Name = "Password Safe v3", Category = "Password Manager", IsSlowHash = true },
        new() { Id = 5300, Name = "IKE-PSK MD5", Category = "Network Protocol" },
        new() { Id = 5400, Name = "IKE-PSK SHA1", Category = "Network Protocol" },
        new() { Id = 5500, Name = "NetNTLMv1 / NetNTLMv1+ESS", Category = "Network Protocol" },
        new() { Id = 5600, Name = "NetNTLMv2", Category = "Network Protocol" },
        new() { Id = 5700, Name = "Cisco-IOS type 4 (SHA256)", Category = "Operating System" },
        new() { Id = 5800, Name = "Samsung Android Password/PIN", Category = "Operating System" },
        new() { Id = 6000, Name = "RIPEMD-160", Category = "Raw Hash" },
        new() { Id = 6100, Name = "Whirlpool", Category = "Raw Hash" },
        new() { Id = 6211, Name = "TrueCrypt RIPEMD160 + XTS 512 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 6212, Name = "TrueCrypt RIPEMD160 + XTS 1024 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 6213, Name = "TrueCrypt RIPEMD160 + XTS 1536 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 6221, Name = "TrueCrypt SHA512 + XTS 512 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 6222, Name = "TrueCrypt SHA512 + XTS 1024 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 6223, Name = "TrueCrypt SHA512 + XTS 1536 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 6231, Name = "TrueCrypt Whirlpool + XTS 512 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 6232, Name = "TrueCrypt Whirlpool + XTS 1024 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 6233, Name = "TrueCrypt Whirlpool + XTS 1536 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 6241, Name = "TrueCrypt RIPEMD160 + XTS 512 bit + boot-mode", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 6242, Name = "TrueCrypt RIPEMD160 + XTS 1024 bit + boot-mode", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 6243, Name = "TrueCrypt RIPEMD160 + XTS 1536 bit + boot-mode", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 6300, Name = "AIX {smd5}", Category = "Operating System" },
        new() { Id = 6400, Name = "AIX {ssha256}", Category = "Operating System", IsSlowHash = true },
        new() { Id = 6500, Name = "AIX {ssha512}", Category = "Operating System", IsSlowHash = true },
        new() { Id = 6600, Name = "1Password, agilekeychain", Category = "Password Manager", IsSlowHash = true },
        new() { Id = 6700, Name = "AIX {ssha1}", Category = "Operating System" },
        new() { Id = 6800, Name = "LastPass + LastPass sniffed", Category = "Password Manager", IsSlowHash = true },
        new() { Id = 6900, Name = "GOST R 34.11-94", Category = "Raw Hash" },
        new() { Id = 7000, Name = "FortiGate (FortiOS)", Category = "Operating System" },
        new() { Id = 7100, Name = "macOS v10.8+ (PBKDF2-SHA512)", Category = "Operating System", IsSlowHash = true },
        new() { Id = 7200, Name = "GRUB 2", Category = "Operating System", IsSlowHash = true },
        new() { Id = 7300, Name = "IPMI2 RAKP HMAC-SHA1", Category = "Network Protocol" },
        new() { Id = 7400, Name = "sha256crypt $5$, SHA256 (Unix)", Category = "Operating System", IsSlowHash = true },
        new() { Id = 7500, Name = "Kerberos 5, etype 23, AS-REQ Pre-Auth", Category = "Network Protocol" },
        new() { Id = 7700, Name = "SAP CODVN B (BCODE)", Category = "Enterprise Application Software (EAS)" },
        new() { Id = 7701, Name = "SAP CODVN B (BCODE) via RFC_READ_TABLE", Category = "Enterprise Application Software (EAS)" },
        new() { Id = 7800, Name = "SAP CODVN F/G (PASSCODE)", Category = "Enterprise Application Software (EAS)" },
        new() { Id = 7801, Name = "SAP CODVN F/G (PASSCODE) via RFC_READ_TABLE", Category = "Enterprise Application Software (EAS)" },
        new() { Id = 7900, Name = "Drupal7", Category = "Forums, CMS, E-Commerce", IsSlowHash = true },
        new() { Id = 8000, Name = "Sybase ASE", Category = "Database Server" },
        new() { Id = 8100, Name = "Citrix NetScaler (SHA1)", Category = "Operating System" },
        new() { Id = 8200, Name = "1Password, cloudkeychain", Category = "Password Manager", IsSlowHash = true },
        new() { Id = 8300, Name = "DNSSEC (NSEC3)", Category = "Network Protocol" },
        new() { Id = 8400, Name = "WBB3 (Woltlab Burning Board)", Category = "Forums, CMS, E-Commerce" },
        new() { Id = 8500, Name = "RACF", Category = "Operating System" },
        new() { Id = 8600, Name = "Lotus Notes/Domino 5", Category = "Enterprise Application Software (EAS)" },
        new() { Id = 8700, Name = "Lotus Notes/Domino 6", Category = "Enterprise Application Software (EAS)" },
        new() { Id = 8800, Name = "Android FDE <= 4.3", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 8900, Name = "scrypt", Category = "Generic KDF", IsSlowHash = true },
        new() { Id = 9000, Name = "Password Safe v2", Category = "Password Manager" },
        new() { Id = 9100, Name = "Lotus Notes/Domino 8", Category = "Enterprise Application Software (EAS)", IsSlowHash = true },
        new() { Id = 9200, Name = "Cisco-IOS $8$ (PBKDF2-SHA256)", Category = "Operating System", IsSlowHash = true },
        new() { Id = 9300, Name = "Cisco-IOS $9$ (scrypt)", Category = "Operating System", IsSlowHash = true },
        new() { Id = 9400, Name = "MS Office 2007", Category = "Document", IsSlowHash = true },
        new() { Id = 9500, Name = "MS Office 2010", Category = "Document", IsSlowHash = true },
        new() { Id = 9600, Name = "MS Office 2013", Category = "Document", IsSlowHash = true },
        new() { Id = 9700, Name = "MS Office <= 2003 $0/$1, MD5 + RC4", Category = "Document" },
        new() { Id = 9710, Name = "MS Office <= 2003 $0/$1, MD5 + RC4, collider #1", Category = "Document" },
        new() { Id = 9720, Name = "MS Office <= 2003 $0/$1, MD5 + RC4, collider #2", Category = "Document" },
        new() { Id = 9800, Name = "MS Office <= 2003 $3/$4, SHA1 + RC4", Category = "Document" },
        new() { Id = 9810, Name = "MS Office <= 2003 $3, SHA1 + RC4, collider #1", Category = "Document" },
        new() { Id = 9820, Name = "MS Office <= 2003 $3, SHA1 + RC4, collider #2", Category = "Document" },
        new() { Id = 9900, Name = "Radmin2", Category = "Operating System" },
        new() { Id = 10000, Name = "Django (PBKDF2-SHA256)", Category = "Framework", IsSlowHash = true },
        new() { Id = 10100, Name = "SipHash", Category = "Raw Hash" },
        new() { Id = 10200, Name = "CRAM-MD5", Category = "Network Protocol" },
        new() { Id = 10300, Name = "SAP CODVN H (PWDSALTEDHASH) iSSHA-1", Category = "Enterprise Application Software (EAS)" },
        new() { Id = 10400, Name = "PDF 1.1 - 1.3 (Acrobat 2 - 4)", Category = "Document" },
        new() { Id = 10410, Name = "PDF 1.1 - 1.3 (Acrobat 2 - 4), collider #1", Category = "Document" },
        new() { Id = 10420, Name = "PDF 1.1 - 1.3 (Acrobat 2 - 4), collider #2", Category = "Document" },
        new() { Id = 10500, Name = "PDF 1.4 - 1.6 (Acrobat 5 - 8)", Category = "Document" },
        new() { Id = 10600, Name = "PDF 1.7 Level 3 (Acrobat 9)", Category = "Document" },
        new() { Id = 10700, Name = "PDF 1.7 Level 8 (Acrobat 10 - 11)", Category = "Document", IsSlowHash = true },
        new() { Id = 10800, Name = "SHA2-384", Category = "Raw Hash" },
        new() { Id = 10900, Name = "PBKDF2-HMAC-SHA256", Category = "Generic KDF", IsSlowHash = true },
        new() { Id = 11000, Name = "PrestaShop", Category = "Forums, CMS, E-Commerce" },
        new() { Id = 11100, Name = "PostgreSQL CRAM (MD5)", Category = "Database Server" },
        new() { Id = 11200, Name = "MySQL CRAM (SHA1)", Category = "Database Server" },
        new() { Id = 11300, Name = "Bitcoin/Litecoin wallet.dat", Category = "Cryptocurrency Wallet", IsSlowHash = true },
        new() { Id = 11400, Name = "SIP digest authentication (MD5)", Category = "Network Protocol" },
        new() { Id = 11500, Name = "CRC32", Category = "Raw Checksum" },
        new() { Id = 11600, Name = "7-Zip", Category = "Archive", IsSlowHash = true },
        new() { Id = 11700, Name = "GOST R 34.11-2012 (Streebog) 256-bit, big-endian", Category = "Raw Hash" },
        new() { Id = 11750, Name = "HMAC-Streebog-256 (key = $pass), big-endian", Category = "Raw Hash, Authenticated" },
        new() { Id = 11760, Name = "HMAC-Streebog-256 (key = $salt), big-endian", Category = "Raw Hash, Authenticated" },
        new() { Id = 11800, Name = "GOST R 34.11-2012 (Streebog) 512-bit, big-endian", Category = "Raw Hash" },
        new() { Id = 11850, Name = "HMAC-Streebog-512 (key = $pass), big-endian", Category = "Raw Hash, Authenticated" },
        new() { Id = 11860, Name = "HMAC-Streebog-512 (key = $salt), big-endian", Category = "Raw Hash, Authenticated" },
        new() { Id = 11900, Name = "PBKDF2-HMAC-MD5", Category = "Generic KDF", IsSlowHash = true },
        new() { Id = 12000, Name = "PBKDF2-HMAC-SHA1", Category = "Generic KDF", IsSlowHash = true },
        new() { Id = 12100, Name = "PBKDF2-HMAC-SHA512", Category = "Generic KDF", IsSlowHash = true },
        new() { Id = 12200, Name = "eCryptfs", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 12300, Name = "Oracle T: Type (Oracle 12+)", Category = "Database Server", IsSlowHash = true },
        new() { Id = 12400, Name = "BSDi Crypt, Extended DES", Category = "Operating System" },
        new() { Id = 12500, Name = "RAR3-hp", Category = "Archive", IsSlowHash = true },
        new() { Id = 12600, Name = "ColdFusion 10+", Category = "FTP, HTTP, SMTP, LDAP Server" },
        new() { Id = 12700, Name = "Blockchain, My Wallet", Category = "Cryptocurrency Wallet", IsSlowHash = true },
        new() { Id = 12800, Name = "MS-AzureSync PBKDF2-HMAC-SHA256", Category = "Operating System", IsSlowHash = true },
        new() { Id = 12900, Name = "Android FDE (Samsung DEK)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 13000, Name = "RAR5", Category = "Archive", IsSlowHash = true },
        new() { Id = 13100, Name = "Kerberos 5, etype 23, TGS-REP", Category = "Network Protocol" },
        new() { Id = 13200, Name = "AxCrypt", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 13300, Name = "AxCrypt in-memory SHA1", Category = "Full-Disk Encryption (FDE)" },
        new() { Id = 13400, Name = "KeePass 1 & 2", Category = "Password Manager", IsSlowHash = true },
        new() { Id = 13500, Name = "PeopleSoft PS_TOKEN", Category = "Enterprise Application Software (EAS)" },
        new() { Id = 13600, Name = "WinZip", Category = "Archive", IsSlowHash = true },
        new() { Id = 13711, Name = "VeraCrypt RIPEMD160 + XTS 512 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 13712, Name = "VeraCrypt RIPEMD160 + XTS 1024 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 13713, Name = "VeraCrypt RIPEMD160 + XTS 1536 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 13721, Name = "VeraCrypt SHA512 + XTS 512 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 13722, Name = "VeraCrypt SHA512 + XTS 1024 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 13723, Name = "VeraCrypt SHA512 + XTS 1536 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 13731, Name = "VeraCrypt Whirlpool + XTS 512 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 13732, Name = "VeraCrypt Whirlpool + XTS 1024 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 13733, Name = "VeraCrypt Whirlpool + XTS 1536 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 13751, Name = "VeraCrypt SHA256 + XTS 512 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 13752, Name = "VeraCrypt SHA256 + XTS 1024 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 13753, Name = "VeraCrypt SHA256 + XTS 1536 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 13761, Name = "VeraCrypt SHA256 + XTS 512 bit + boot-mode", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 13762, Name = "VeraCrypt SHA256 + XTS 1024 bit + boot-mode", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 13763, Name = "VeraCrypt SHA256 + XTS 1536 bit + boot-mode", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 13800, Name = "Windows Phone 8+ PIN/password", Category = "Operating System", IsSlowHash = true },
        new() { Id = 13900, Name = "OpenCart", Category = "Forums, CMS, E-Commerce" },
        new() { Id = 14000, Name = "DES (PT = $salt, key = $pass)", Category = "Raw Cipher, Known Plaintext" },
        new() { Id = 14100, Name = "3DES (PT = $salt, key = $pass)", Category = "Raw Cipher, Known Plaintext" },
        new() { Id = 14400, Name = "sha1(CX)", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 14600, Name = "LUKS", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 14700, Name = "iTunes backup < 10.0", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 14800, Name = "iTunes backup >= 10.0", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 14900, Name = "Skip32 (PT = $salt, key = $pass)", Category = "Raw Cipher, Known Plaintext" },
        new() { Id = 15000, Name = "FileZilla Server >= 0.9.55", Category = "FTP, HTTP, SMTP, LDAP Server" },
        new() { Id = 15100, Name = "Juniper/NetBSD sha1crypt", Category = "Operating System" },
        new() { Id = 15200, Name = "Blockchain, My Wallet, V2", Category = "Cryptocurrency Wallet", IsSlowHash = true },
        new() { Id = 15300, Name = "DPAPI masterkey file v1", Category = "Operating System", IsSlowHash = true },
        new() { Id = 15400, Name = "ChaCha20", Category = "Raw Cipher, Known Plaintext" },
        new() { Id = 15500, Name = "JKS Java Key Store Private Keys (SHA1)", Category = "Password Manager" },
        new() { Id = 15600, Name = "Ethereum Wallet, PBKDF2-HMAC-SHA256", Category = "Cryptocurrency Wallet", IsSlowHash = true },
        new() { Id = 15700, Name = "Ethereum Wallet, SCRYPT", Category = "Cryptocurrency Wallet", IsSlowHash = true },
        new() { Id = 15900, Name = "DPAPI masterkey file v2", Category = "Operating System", IsSlowHash = true },
        new() { Id = 16000, Name = "Tripcode", Category = "Forums, CMS, E-Commerce" },
        new() { Id = 16100, Name = "TACACS+", Category = "Network Protocol" },
        new() { Id = 16200, Name = "Apple Secure Notes", Category = "Password Manager", IsSlowHash = true },
        new() { Id = 16300, Name = "Ethereum Pre-Sale Wallet, PBKDF2-HMAC-SHA256", Category = "Cryptocurrency Wallet", IsSlowHash = true },
        new() { Id = 16400, Name = "CRAM-MD5 Dovecot", Category = "FTP, HTTP, SMTP, LDAP Server" },
        new() { Id = 16500, Name = "JWT (JSON Web Token)", Category = "Network Protocol" },
        new() { Id = 16600, Name = "Electrum Wallet (Salt-Type 1-3)", Category = "Cryptocurrency Wallet", IsSlowHash = true },
        new() { Id = 16700, Name = "FileVault 2", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 16800, Name = "WPA-PMKID-PBKDF2", Category = "Network Protocol", IsSlowHash = true },
        new() { Id = 16801, Name = "WPA-PMKID-PMK", Category = "Network Protocol" },
        new() { Id = 16900, Name = "Ansible Vault", Category = "Password Manager", IsSlowHash = true },
        new() { Id = 17200, Name = "PKZIP (Compressed)", Category = "Archive" },
        new() { Id = 17210, Name = "PKZIP (Uncompressed)", Category = "Archive" },
        new() { Id = 17220, Name = "PKZIP (Compressed Multi-File)", Category = "Archive" },
        new() { Id = 17225, Name = "PKZIP (Mixed Multi-File)", Category = "Archive" },
        new() { Id = 17230, Name = "PKZIP (Mixed Multi-File Checksum-Only)", Category = "Archive" },
        new() { Id = 17300, Name = "SHA3-224", Category = "Raw Hash" },
        new() { Id = 17400, Name = "SHA3-256", Category = "Raw Hash" },
        new() { Id = 17500, Name = "SHA3-384", Category = "Raw Hash" },
        new() { Id = 17600, Name = "SHA3-512", Category = "Raw Hash" },
        new() { Id = 17700, Name = "Keccak-224", Category = "Raw Hash" },
        new() { Id = 17800, Name = "Keccak-256", Category = "Raw Hash" },
        new() { Id = 17900, Name = "Keccak-384", Category = "Raw Hash" },
        new() { Id = 18000, Name = "Keccak-512", Category = "Raw Hash" },
        new() { Id = 18100, Name = "TOTP (HMAC-SHA1)", Category = "One-Time Password" },
        new() { Id = 18200, Name = "Kerberos 5, etype 23, AS-REP", Category = "Network Protocol" },
        new() { Id = 18300, Name = "Apple File System (APFS)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 18400, Name = "Open Document Format (ODF) 1.2 (SHA-256, AES)", Category = "Document", IsSlowHash = true },
        new() { Id = 18500, Name = "sha1(md5(md5($pass)))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 18600, Name = "Open Document Format (ODF) 1.1 (SHA-1, Blowfish)", Category = "Document" },
        new() { Id = 18700, Name = "Java Object hashCode()", Category = "Raw Hash" },
        new() { Id = 18800, Name = "Blockchain, My Wallet, Second Password (SHA256)", Category = "Cryptocurrency Wallet", IsSlowHash = true },
        new() { Id = 18900, Name = "Android Backup", Category = "Operating System", IsSlowHash = true },
        new() { Id = 19000, Name = "QNX /etc/shadow (MD5)", Category = "Operating System" },
        new() { Id = 19100, Name = "QNX /etc/shadow (SHA256)", Category = "Operating System", IsSlowHash = true },
        new() { Id = 19200, Name = "QNX /etc/shadow (SHA512)", Category = "Operating System", IsSlowHash = true },
        new() { Id = 19300, Name = "sha1($salt1.$pass.$salt2)", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 19500, Name = "Ruby on Rails Restful-Authentication", Category = "Framework" },
        new() { Id = 19600, Name = "Kerberos 5, etype 17, TGS-REP", Category = "Network Protocol" },
        new() { Id = 19700, Name = "Kerberos 5, etype 18, TGS-REP", Category = "Network Protocol" },
        new() { Id = 19800, Name = "Kerberos 5, etype 17, Pre-Auth", Category = "Network Protocol" },
        new() { Id = 19900, Name = "Kerberos 5, etype 18, Pre-Auth", Category = "Network Protocol" },
        new() { Id = 20011, Name = "DiskCryptor SHA512 + XTS 512 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 20012, Name = "DiskCryptor SHA512 + XTS 1024 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 20013, Name = "DiskCryptor SHA512 + XTS 1536 bit", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 20200, Name = "Python passlib pbkdf2-sha512", Category = "Framework", IsSlowHash = true },
        new() { Id = 20300, Name = "Python passlib pbkdf2-sha256", Category = "Framework", IsSlowHash = true },
        new() { Id = 20400, Name = "Python passlib pbkdf2-sha1", Category = "Framework", IsSlowHash = true },
        new() { Id = 20500, Name = "PKZIP Master Key", Category = "Archive" },
        new() { Id = 20510, Name = "PKZIP Master Key (6 byte optimization)", Category = "Archive" },
        new() { Id = 20600, Name = "Oracle Transportation Management (SHA256)", Category = "Enterprise Application Software (EAS)" },
        new() { Id = 20710, Name = "sha256(sha256($pass).$salt)", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 20711, Name = "AuthMe sha256", Category = "Forums, CMS, E-Commerce" },
        new() { Id = 20720, Name = "sha256($salt.sha256($pass))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 20800, Name = "sha256(md5($pass))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 20900, Name = "md5(sha1($pass).md5($pass).sha1($pass))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 21000, Name = "BitShares v0.x", Category = "Cryptocurrency Wallet" },
        new() { Id = 21100, Name = "sha1(md5($salt.$pass))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 21200, Name = "md5(sha1($salt).md5($pass))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 21300, Name = "md5($salt.sha1($salt.$pass))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 21400, Name = "sha256(sha256_bin($pass))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 21500, Name = "SolarWinds Orion", Category = "Enterprise Application Software (EAS)" },
        new() { Id = 21501, Name = "SolarWinds Orion v2", Category = "Enterprise Application Software (EAS)" },
        new() { Id = 21600, Name = "Web2py pbkdf2-sha512", Category = "Framework", IsSlowHash = true },
        new() { Id = 21700, Name = "Electrum Wallet (Salt-Type 4)", Category = "Cryptocurrency Wallet", IsSlowHash = true },
        new() { Id = 21800, Name = "Electrum Wallet (Salt-Type 5)", Category = "Cryptocurrency Wallet", IsSlowHash = true },
        new() { Id = 22000, Name = "WPA-PBKDF2-PMKID+EAPOL", Category = "Network Protocol", IsSlowHash = true },
        new() { Id = 22001, Name = "WPA-PMK-PMKID+EAPOL", Category = "Network Protocol" },
        new() { Id = 22100, Name = "BitLocker", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 22200, Name = "Citrix NetScaler (SHA512)", Category = "Operating System" },
        new() { Id = 22300, Name = "sha256($salt.$pass.$salt)", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 22400, Name = "AES Crypt (SHA256)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 22500, Name = "MultiBit Classic .key (MD5)", Category = "Cryptocurrency Wallet" },
        new() { Id = 22600, Name = "Telegram Desktop App Passcode (PBKDF2-HMAC-SHA1)", Category = "Instant Messaging", IsSlowHash = true },
        new() { Id = 22700, Name = "MultiBit HD (scrypt)", Category = "Cryptocurrency Wallet", IsSlowHash = true },
        new() { Id = 22911, Name = "RSA/DSA/EC/OpenSSH Private Keys ($0$)", Category = "Private Key" },
        new() { Id = 22921, Name = "RSA/DSA/EC/OpenSSH Private Keys ($6$)", Category = "Private Key", IsSlowHash = true },
        new() { Id = 22931, Name = "RSA/DSA/EC/OpenSSH Private Keys ($1, $3$)", Category = "Private Key" },
        new() { Id = 22941, Name = "RSA/DSA/EC/OpenSSH Private Keys ($4$)", Category = "Private Key" },
        new() { Id = 22951, Name = "RSA/DSA/EC/OpenSSH Private Keys ($5$)", Category = "Private Key" },
        new() { Id = 23001, Name = "SecureZIP AES-128", Category = "Archive", IsSlowHash = true },
        new() { Id = 23002, Name = "SecureZIP AES-192", Category = "Archive", IsSlowHash = true },
        new() { Id = 23003, Name = "SecureZIP AES-256", Category = "Archive", IsSlowHash = true },
        new() { Id = 23100, Name = "Apple Keychain", Category = "Password Manager", IsSlowHash = true },
        new() { Id = 23200, Name = "XMPP SCRAM PBKDF2-SHA1", Category = "Instant Messaging", IsSlowHash = true },
        new() { Id = 23300, Name = "Apple iWork", Category = "Document", IsSlowHash = true },
        new() { Id = 23400, Name = "Bitwarden", Category = "Password Manager", IsSlowHash = true },
        new() { Id = 23500, Name = "AxCrypt 2 AES-128", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 23600, Name = "AxCrypt 2 AES-256", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 23700, Name = "RAR3-p (Uncompressed)", Category = "Archive", IsSlowHash = true },
        new() { Id = 23800, Name = "RAR3-p (Compressed)", Category = "Archive", IsSlowHash = true },
        new() { Id = 23900, Name = "BestCrypt v3 Volume Encryption", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 24100, Name = "MongoDB ServerKey SCRAM-SHA-1", Category = "Database Server", IsSlowHash = true },
        new() { Id = 24200, Name = "MongoDB ServerKey SCRAM-SHA-256", Category = "Database Server", IsSlowHash = true },
        new() { Id = 24300, Name = "SHA1($salt.sha1($pass.$salt))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 24410, Name = "PKCS#8 Private Keys (PBKDF2-HMAC-SHA1 + 3DES/AES)", Category = "Private Key", IsSlowHash = true },
        new() { Id = 24420, Name = "PKCS#8 Private Keys (PBKDF2-HMAC-SHA256 + 3DES/AES)", Category = "Private Key", IsSlowHash = true },
        new() { Id = 24500, Name = "Telegram Desktop >= v2.1.14", Category = "Instant Messaging", IsSlowHash = true },
        new() { Id = 24600, Name = "SQLCipher", Category = "Database Server", IsSlowHash = true },
        new() { Id = 24700, Name = "Stuffit5", Category = "Archive" },
        new() { Id = 24800, Name = "Umbraco HMAC-SHA1", Category = "Forums, CMS, E-Commerce" },
        new() { Id = 24900, Name = "Dahua Authentication MD5", Category = "Network Protocol" },
        new() { Id = 25000, Name = "SNMPv3 HMAC-MD5-96/HMAC-SHA1-96", Category = "Network Protocol" },
        new() { Id = 25100, Name = "SNMPv3 HMAC-MD5-96", Category = "Network Protocol" },
        new() { Id = 25200, Name = "SNMPv3 HMAC-SHA1-96", Category = "Network Protocol" },
        new() { Id = 25300, Name = "MS Office 2016 - SheetProtection", Category = "Document" },
        new() { Id = 25400, Name = "PDF 1.4 - 1.6 (Acrobat 5 - 8) - user and owner pass", Category = "Document" },
        new() { Id = 25500, Name = "Stargazer Stellar Wallet XLM", Category = "Cryptocurrency Wallet", IsSlowHash = true },
        new() { Id = 25600, Name = "bcrypt(md5($pass)) / bcryptmd5", Category = "Forums, CMS, E-Commerce", IsSlowHash = true },
        new() { Id = 25700, Name = "MurmurHash", Category = "Raw Hash" },
        new() { Id = 25800, Name = "bcrypt(sha1($pass)) / bcryptsha1", Category = "Forums, CMS, E-Commerce", IsSlowHash = true },
        new() { Id = 25900, Name = "KNX IP Secure - Device Authentication Code", Category = "Network Protocol" },
        new() { Id = 26000, Name = "Mozilla key3.db", Category = "Password Manager" },
        new() { Id = 26100, Name = "Mozilla key4.db", Category = "Password Manager" },
        new() { Id = 26200, Name = "OpenEdge Progress Encode", Category = "Enterprise Application Software (EAS)" },
        new() { Id = 26300, Name = "FortiGate256 (FortiOS256)", Category = "Operating System" },
        new() { Id = 26401, Name = "AES-128-CBC-HMAC-SHA256", Category = "Raw Cipher, Known Plaintext" },
        new() { Id = 26402, Name = "AES-192-CBC-HMAC-SHA256", Category = "Raw Cipher, Known Plaintext" },
        new() { Id = 26403, Name = "AES-256-CBC-HMAC-SHA256", Category = "Raw Cipher, Known Plaintext" },
        new() { Id = 26500, Name = "iPhone passcode (UID key + System Keybag)", Category = "Operating System", IsSlowHash = true },
        new() { Id = 26600, Name = "MetaMask Wallet", Category = "Cryptocurrency Wallet", IsSlowHash = true },
        new() { Id = 26700, Name = "SNMPv3 HMAC-SHA224-128", Category = "Network Protocol" },
        new() { Id = 26800, Name = "SNMPv3 HMAC-SHA256-192", Category = "Network Protocol" },
        new() { Id = 26900, Name = "SNMPv3 HMAC-SHA384-256", Category = "Network Protocol" },
        new() { Id = 27000, Name = "NetNTLMv1 / NetNTLMv1+ESS (NT)", Category = "Network Protocol" },
        new() { Id = 27100, Name = "NetNTLMv2 (NT)", Category = "Network Protocol" },
        new() { Id = 27200, Name = "Ruby on Rails Restful Auth (one round)", Category = "Framework" },
        new() { Id = 27300, Name = "SNMPv3 HMAC-SHA512-384", Category = "Network Protocol" },
        new() { Id = 27400, Name = "VMware VMX (PBKDF2-HMAC-SHA1 + AES-256-CBC)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 27500, Name = "VirtualBox (PBKDF2-HMAC-SHA256 & AES-128-XTS)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 27600, Name = "VirtualBox (PBKDF2-HMAC-SHA256 & AES-256-XTS)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 27700, Name = "MultiBit Classic .wallet (scrypt)", Category = "Cryptocurrency Wallet", IsSlowHash = true },
        new() { Id = 27800, Name = "MurmurHash3", Category = "Raw Hash" },
        new() { Id = 27900, Name = "CRC32C", Category = "Raw Checksum" },
        new() { Id = 28000, Name = "CRC64Jones", Category = "Raw Checksum" },
        new() { Id = 28100, Name = "Windows Hello PIN/Password", Category = "Operating System", IsSlowHash = true },
        new() { Id = 28200, Name = "Exodus Desktop Wallet (scrypt)", Category = "Cryptocurrency Wallet", IsSlowHash = true },
        new() { Id = 28300, Name = "Teamspeak 3 (channel hash)", Category = "Instant Messaging" },
        new() { Id = 28400, Name = "bcrypt(sha512($pass)) / bcryptsha512", Category = "Forums, CMS, E-Commerce", IsSlowHash = true },
        new() { Id = 28501, Name = "Bitcoin WIF private key (P2PKH), compressed", Category = "Cryptocurrency Wallet" },
        new() { Id = 28502, Name = "Bitcoin WIF private key (P2PKH), uncompressed", Category = "Cryptocurrency Wallet" },
        new() { Id = 28503, Name = "Bitcoin WIF private key (P2WPKH, Bech32), compressed", Category = "Cryptocurrency Wallet" },
        new() { Id = 28504, Name = "Bitcoin WIF private key (P2WPKH, Bech32), uncompressed", Category = "Cryptocurrency Wallet" },
        new() { Id = 28505, Name = "Bitcoin WIF private key (P2SH(P2WPKH)), compressed", Category = "Cryptocurrency Wallet" },
        new() { Id = 28506, Name = "Bitcoin WIF private key (P2SH(P2WPKH)), uncompressed", Category = "Cryptocurrency Wallet" },
        new() { Id = 28600, Name = "PostgreSQL SCRAM-SHA-256", Category = "Database Server", IsSlowHash = true },
        new() { Id = 28700, Name = "Amazon AWS4-HMAC-SHA256", Category = "Network Protocol" },
        new() { Id = 28800, Name = "Kerberos 5, etype 17, DB", Category = "Network Protocol" },
        new() { Id = 28900, Name = "Kerberos 5, etype 18, DB", Category = "Network Protocol" },
        new() { Id = 29000, Name = "sha1($salt.sha1(utf16le($username).':'.utf16le($pass)))", Category = "Raw Hash, Salted and/or Iterated" },
        new() { Id = 29100, Name = "Flask Session Cookie ($salt.$salt.$pass)", Category = "Network Protocol" },
        new() { Id = 29200, Name = "Radmin3", Category = "Operating System", IsSlowHash = true },
        new() { Id = 29311, Name = "TrueCrypt RIPEMD160 + XTS 512 bit + boot-mode", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29312, Name = "TrueCrypt RIPEMD160 + XTS 1024 bit + boot-mode", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29313, Name = "TrueCrypt RIPEMD160 + XTS 1536 bit + boot-mode", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29321, Name = "TrueCrypt SHA512 + XTS 512 bit + boot-mode", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29322, Name = "TrueCrypt SHA512 + XTS 1024 bit + boot-mode", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29323, Name = "TrueCrypt SHA512 + XTS 1536 bit + boot-mode", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29331, Name = "TrueCrypt Whirlpool + XTS 512 bit + boot-mode", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29332, Name = "TrueCrypt Whirlpool + XTS 1024 bit + boot-mode", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29333, Name = "TrueCrypt Whirlpool + XTS 1536 bit + boot-mode", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29341, Name = "TrueCrypt RIPEMD160 + XTS 512 bit + full disk encryption", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29342, Name = "TrueCrypt RIPEMD160 + XTS 1024 bit + full disk encryption", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29343, Name = "TrueCrypt RIPEMD160 + XTS 1536 bit + full disk encryption", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29411, Name = "VeraCrypt RIPEMD160 + XTS 512 bit + boot-mode (PIM enabled)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29412, Name = "VeraCrypt RIPEMD160 + XTS 1024 bit + boot-mode (PIM enabled)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29413, Name = "VeraCrypt RIPEMD160 + XTS 1536 bit + boot-mode (PIM enabled)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29421, Name = "VeraCrypt SHA512 + XTS 512 bit + boot-mode (PIM enabled)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29422, Name = "VeraCrypt SHA512 + XTS 1024 bit + boot-mode (PIM enabled)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29423, Name = "VeraCrypt SHA512 + XTS 1536 bit + boot-mode (PIM enabled)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29431, Name = "VeraCrypt Whirlpool + XTS 512 bit + boot-mode (PIM enabled)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29432, Name = "VeraCrypt Whirlpool + XTS 1024 bit + boot-mode (PIM enabled)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29433, Name = "VeraCrypt Whirlpool + XTS 1536 bit + boot-mode (PIM enabled)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29441, Name = "VeraCrypt RIPEMD160 + XTS 512 bit + full disk encryption (PIM)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29442, Name = "VeraCrypt RIPEMD160 + XTS 1024 bit + full disk encryption (PIM)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29443, Name = "VeraCrypt RIPEMD160 + XTS 1536 bit + full disk encryption (PIM)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29451, Name = "VeraCrypt SHA256 + XTS 512 bit + boot-mode (PIM enabled)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29452, Name = "VeraCrypt SHA256 + XTS 1024 bit + boot-mode (PIM enabled)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29453, Name = "VeraCrypt SHA256 + XTS 1536 bit + boot-mode (PIM enabled)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29461, Name = "VeraCrypt SHA256 + XTS 512 bit + full disk encryption (PIM)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29462, Name = "VeraCrypt SHA256 + XTS 1024 bit + full disk encryption (PIM)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29463, Name = "VeraCrypt SHA256 + XTS 1536 bit + full disk encryption (PIM)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29471, Name = "VeraCrypt Streebog-512 + XTS 512 bit + boot-mode (PIM enabled)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29472, Name = "VeraCrypt Streebog-512 + XTS 1024 bit + boot-mode (PIM enabled)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29473, Name = "VeraCrypt Streebog-512 + XTS 1536 bit + boot-mode (PIM enabled)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29481, Name = "VeraCrypt Streebog-512 + XTS 512 bit + full disk encryption (PIM)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29482, Name = "VeraCrypt Streebog-512 + XTS 1024 bit + full disk encryption (PIM)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29483, Name = "VeraCrypt Streebog-512 + XTS 1536 bit + full disk encryption (PIM)", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29511, Name = "LUKS v1 SHA-1 + AES", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29512, Name = "LUKS v1 SHA-1 + Serpent", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29513, Name = "LUKS v1 SHA-1 + Twofish", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29521, Name = "LUKS v1 SHA-256 + AES", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29522, Name = "LUKS v1 SHA-256 + Serpent", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29523, Name = "LUKS v1 SHA-256 + Twofish", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29531, Name = "LUKS v1 SHA-512 + AES", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29532, Name = "LUKS v1 SHA-512 + Serpent", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29533, Name = "LUKS v1 SHA-512 + Twofish", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29541, Name = "LUKS v1 RIPEMD-160 + AES", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29542, Name = "LUKS v1 RIPEMD-160 + Serpent", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29543, Name = "LUKS v1 RIPEMD-160 + Twofish", Category = "Full-Disk Encryption (FDE)", IsSlowHash = true },
        new() { Id = 29600, Name = "Terra Station Wallet (AES256-CBC(PBKDF2($pass)))", Category = "Cryptocurrency Wallet", IsSlowHash = true },
        new() { Id = 29700, Name = "KeePass 1 (AES/Twofish) and KeePass 2 (AES) - keyfile-only mode", Category = "Password Manager", IsSlowHash = true },
        new() { Id = 29800, Name = "Bisq", Category = "Cryptocurrency Wallet", IsSlowHash = true },
        new() { Id = 29900, Name = "RAR3-p (Compressed)", Category = "Archive", IsSlowHash = true },
        new() { Id = 29910, Name = "RAR3-p (Uncompressed)", Category = "Archive", IsSlowHash = true },
        new() { Id = 99999, Name = "Plaintext", Category = "Plaintext" },
    };

    public static List<string> GetCategories() => GetAllModes()
        .Select(m => m.Category)
        .Distinct()
        .OrderBy(c => c)
        .ToList();

    public static List<HashMode> GetByCategory(string category) => GetAllModes()
        .Where(m => m.Category == category)
        .ToList();
}
